language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g gulp
  - npm install -g karma
  - npm install -g bower

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install
 - bower install

script:
 - gulp html2js
 - gulp travis

after_success:
	cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
